apiVersion: v1
kind: Namespace
metadata:
  name: clusterpedia-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterpedia-internalstorage
  namespace: clusterpedia-system
data:
  internalstorage-config.yaml: |
    type: "mysql"
    host: "10.106.125.84"
    port: 3306
    user: root
    database: "clusterpedia"
